name: arch-pkg
on: [push, pull_request]

jobs:
  arch-pkg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Arch Linux package
        uses: 2m/arch-pkgbuild-builder@v1.21
        with:
          target: 'pkgbuild'
          pkgname: '.github/archlinux'


